### ISSUE TITLE
Issues with python-redfish-utility on Mac OS High Sierra

### ISSUE THREAD

**Issue by TommyKTheDJ** [HewlettPackard/python-redfish-utility#6]
I have run the following:
$ pip install pyinstaller
$ pyinstaller rdmc-pyinstaller-mac.spec
(using the version cloned from this repo)
Am getting a series of errors - full output can be found here: https://gist.github.com/TommyKTheDJ/50ba1c44ca3175b7be8255827672bb99

But boils down to a series of errors like this:
ERROR: Hidden import 'extensions.Users.kivlint..virtualenvs.redfish.python-redfish-utility.LICENSE.md' not found

And then:
ImportError: No module named six

And: 
AttributeError: 'str' object has no attribute 'items'

**Comment by Yergidy** [comment]
python-redfish-utility requires the python-ilorest-library and a few other packages in order to function properly. I will be documenting what is required in the README.

Requires:
python-ilorest-library (pip install python-ilorest-library)
readline (pip install readline)
setproctitle (pip install setproctitle)
pyudev (pip install pyudev)
jsondiff (pip install jsondiff)
pyaes (pip install pyaes)

If you are not making any changes to the source I recommend using one of our binaries. We include a .pkg installer for Mac:
https://github.com/HewlettPackard/python-redfish-utility/releases/tag/v2.3.1

**Comment by TommyKTheDJ** [comment]
Ah perfect, thanks - I have now got it working.
